---
title: "Tables for MS"
author: "D. Craven et al."
date: "April 26, 2018"
output: 
  word_document: 
    fig_caption: yes
    fig_height: 6
    highlight: monochrome
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(knitr,quietly = TRUE)
require(dplyr,quietly = TRUE)
require(tidyr, quietly=TRUE)

```

**Table 1.**  Summary of number of plots, sampled area, and environmental conditions across forest plots in the Hawaiian archipelago.   
```{r, echo=FALSE}

haw_study<-read.csv("/home/dylan/Dropbox (iDiv)/Research_projects/Veg. monitoring databases/databases and field protocols/database/IslandForests/Hawaii_only/Diversity_Age/Hawaii_diversity/Cleaned_Data/Scen1_Natives_EnvConditions.csv")

haw_study$geo_entity2<-factor(haw_study$geo_entity2, levels=c("Hawai'i Island","Maui Nui", "O'ahu Island", "Kaua'i Island"))

haw_study$totPlotArea<-round(haw_study$totPlotArea, digits=0)
haw_study$mean_MAT<-round(haw_study$mean_MAT, digits=1)
haw_study$mean_MAP<-round(haw_study$mean_MAP, digits=0)
haw_study$mean_PET<-round(haw_study$mean_PET, digits=0)
haw_study$r_PET<-round(haw_study$r_PET, digits=0)
haw_study$max_Elev<-round(haw_study$max_Elev, digits=0)


haw_study<-select(haw_study, "Islands"=geo_entity2,"Plots (#)"=PlotN, "Sampled area (m2)"=totPlotArea, "Individuals (#)"= Abundance_tot_raw, 
                  "MAT (C)"=mean_MAT, "MAP (mm yr-1)"=mean_MAP, "PET (mm yr-1)"=mean_PET, "PET range"=r_PET,"Max. elevation (m)"=max_Elev)

haw_study<-kable(haw_study,format="markdown",align="c",digits=1, caption="Table 1.  Summary of number of plots, sampled area, and environmental conditions across forest plots in the Hawaiian archipelago.")
haw_study

```


**Table 2.** Sampled area, number of plots, and number of individuals and species per island across the Hawaiian archipelago.      
```{r, echo=FALSE}
haw_scen1<-read.csv("/home/dylan/Dropbox (iDiv)/Research_projects/Veg. monitoring databases/databases and field protocols/database/IslandForests/Hawaii_only/Diversity_Age/Hawaii_diversity/Cleaned_Data/Scen1_Natives_EnvConditions.csv")
haw_scen1<-select(haw_scen1, geo_entity2, "PlotArea_Scen1"=totPlotArea,"meanPET_scen1"=mean_PET, "rangePET_scen1"=r_PET)

haw_scen2<-read.table("/home/dylan/Dropbox (iDiv)/Research_projects/Veg. monitoring databases/databases and field protocols/database/IslandForests/Hawaii_only/Diversity_Age/Hawaii_diversity/Cleaned_Data/Scen2_Natives_7plots_Envconditions_summarized.csv",sep=",",header=T)
haw_scen2<-select(haw_scen2, geo_entity2, "PlotArea_Scen2"=m_PlotArea,"meanPET_scen2"=mean_PET, "rangePET_scen2"=r_PET)

haw_scen3<-read.table("/home/dylan/Dropbox (iDiv)/Research_projects/Veg. monitoring databases/databases and field protocols/database/IslandForests/Hawaii_only/Diversity_Age/Hawaii_diversity/Cleaned_Data/Scen3_Native_7plots_EnvConditions_summarized.csv",sep=",",header=T)
haw_scen3<-select(haw_scen3, geo_entity2, "PlotArea_Scen3"=m_PlotArea,"meanPET_scen3"=mean_PET, "rangePET_scen3"=r_PET)

haw_scenn<-left_join(haw_scen1,haw_scen2,by="geo_entity2")%>%
            left_join(.,haw_scen3, by="geo_entity2")

haw_scenn$geo_entity2<-factor(haw_scenn$geo_entity2, levels=c("Hawai'i Island","Maui Nui", "O'ahu Island", "Kaua'i Island"))

haw_scenn$PlotArea_Scen1<-round(haw_scenn$PlotArea_Scen1, digits=0)
haw_scenn$meanPET_scen1<-round(haw_scenn$meanPET_scen1, digits=0)
haw_scenn$rangePET_scen1<-round(haw_scenn$rangePET_scen1, digits=0)

haw_scenn$PlotArea_Scen2<-round(haw_scenn$PlotArea_Scen2, digits=0)
haw_scenn$meanPET_scen2<-round(haw_scenn$meanPET_scen2, digits=0)
haw_scenn$rangePET_scen2<-round(haw_scenn$rangePET_scen2, digits=0)

haw_scenn$PlotArea_Scen3<-round(haw_scenn$PlotArea_Scen3, digits=0)
haw_scenn$meanPET_scen3<-round(haw_scenn$meanPET_scen3, digits=0)
haw_scenn$rangePET_scen3<-round(haw_scenn$rangePET_scen3, digits=0)


haw_scenn<-kable(haw_scenn,format="markdown",align="c",digits=1, caption="Table 2. Summary of sampled area and the range and mean of PET for each sampling scenario across forest plots in the Hawaiian archipelago.")
haw_scenn


```
